language: python
python:
  - "3.6"

install:
  - pip install kodi-addon-checker

before_script:
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      export ADDON_CHECK_PARAMETERS="--branch=krypton";
    else
      export ADDON_CHECK_PARAMETERS="--branch=krypton --PR $(git diff --diff-filter=d --name-only HEAD~ | grep / | cut -d / -f1 | sort | uniq)";
    fi
# command to run our tests
script:
- kodi-addon-checker $ADDON_CHECK_PARAMETERS

notifications:
  webhooks: https://www.travisbuddy.com/
  email:
    on_failure: change # default: always

travisBuddy:
successBuildLog: "true"
